use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;
use std::net::IpAddr;

use anyhow::{Result, bail};

use crate::nodes::Proxy;
use crate::surge::{node_selector, sanitize_policy_name};

pub fn render_provider(
    proxies: &[Proxy],
    listen_address: &str,
    port: u16,
    routing_secret: &str,
) -> Result<Vec<u8>> {
    let ip: IpAddr = listen_address
        .parse()
        .map_err(|_| anyhow::anyhow!("Clash provider requires a specific numeric SOCKS5 IP"))?;
    if ip.is_unspecified() || ip.is_multicast() {
        bail!("Clash provider requires a specific numeric SOCKS5 IP");
    }
    if port == 0 {
        bail!("Clash provider SOCKS5 port cannot be zero");
    }
    if proxies.is_empty() {
        bail!("Clash provider requires at least one node");
    }
    if !is_safe_credential(routing_secret) {
        bail!("Clash provider routing secret is invalid");
    }

    let mut selectors = HashSet::with_capacity(proxies.len());
    let mut names = HashMap::<String, usize>::with_capacity(proxies.len());
    let mut rendered = Vec::with_capacity(proxies.len());
    for proxy in proxies {
        let selector = node_selector(&proxy.name)?;
        if !selectors.insert(selector.clone()) {
            bail!("Clash provider selector collision");
        }
        let policy_name = sanitize_policy_name(&proxy.name);
        *names.entry(policy_name.clone()).or_default() += 1;
        rendered.push((policy_name, selector));
    }

    let mut output = String::from("# Generated by oixc-proxy. Do not edit.\nproxies:\n");
    for (proxy, (mut policy_name, selector)) in proxies.iter().zip(rendered) {
        if names[&policy_name] > 1 {
            write!(policy_name, " [{selector}]")?;
        }
        writeln!(output, "- name: {}", yaml_quote(&policy_name))?;
        writeln!(output, "  type: socks5")?;
        writeln!(output, "  server: {listen_address}")?;
        writeln!(output, "  port: {port}")?;
        writeln!(output, "  username: {selector}")?;
        writeln!(output, "  password: {routing_secret}")?;
        writeln!(output, "  udp: {}", proxy.udp)?;
    }
    Ok(output.into_bytes())
}

fn yaml_quote(value: &str) -> String {
    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('"');
    for character in value.chars() {
        match character {
            '"' => quoted.push_str("\\\""),
            '\\' => quoted.push_str("\\\\"),
            character if (character as u32) < 0x20 => {
                let _ = write!(quoted, "\\u{:04x}", character as u32);
            }
            character => quoted.push(character),
        }
    }
    quoted.push('"');
    quoted
}

fn is_safe_credential(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 255
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::nodes::ObfsOptions;

    fn proxy(name: &str, udp: bool) -> Proxy {
        Proxy {
            name: name.to_owned(),
            proxy_type: "snell".to_owned(),
            server: "node.example.com".to_owned(),
            port: 443,
            psk: "psk".to_owned(),
            version: 4,
            udp,
            tfo: false,
            reuse: true,
            identity: true,
            obfs: ObfsOptions {
                mode: "ech-tls".to_owned(),
                sni: "sni.example.com".to_owned(),
                path: "/".to_owned(),
                alpn: "snell-ech/1".to_owned(),
                ech_config: "config".to_owned(),
                identity_version: 2,
                legacy_fallback: false,
                skip_cert_verify: false,
                preconnect: 0,
            },
        }
    }

    #[test]
    fn renders_clash_provider_yaml() {
        let proxies = [proxy("🇭🇰 Hong Kong 01", true), proxy("US \"West\"", false)];
        let output = render_provider(&proxies, "127.0.0.1", 6178, "secret-1").unwrap();
        let output = String::from_utf8(output).unwrap();
        assert!(output.starts_with("# Generated by oixc-proxy. Do not edit.\nproxies:\n"));
        assert!(output.contains("- name: \"🇭🇰 Hong Kong 01\"\n"));
        assert!(output.contains("- name: \"US \\\"West\\\"\"\n"));
        assert!(output.contains("  type: socks5\n"));
        assert!(output.contains("  server: 127.0.0.1\n"));
        assert!(output.contains("  port: 6178\n"));
        assert!(output.contains("  password: secret-1\n"));
        assert!(output.contains("  udp: true\n"));
        assert!(output.contains("  udp: false\n"));
        assert!(output.contains(&format!(
            "  username: {}\n",
            node_selector("🇭🇰 Hong Kong 01").unwrap()
        )));
    }

    #[test]
    fn duplicate_display_names_get_selector_suffix() {
        let proxies = [proxy("Node,A", false), proxy("Node=A", false)];
        let output = render_provider(&proxies, "127.0.0.1", 6178, "secret-1").unwrap();
        let output = String::from_utf8(output).unwrap();
        assert!(output.contains(&format!(
            "- name: \"Node A [{}]\"\n",
            node_selector("Node,A").unwrap()
        )));
        assert!(output.contains(&format!(
            "- name: \"Node A [{}]\"\n",
            node_selector("Node=A").unwrap()
        )));
    }
}
